### ISSUE TITLE
Blinking in polygonmap

### ISSUE THREAD

**Issue by twolfvb** [niclabs/net-viz#33]
When you hover your mouse over the polygonmap, sometimes it will start blinking.
If you place your mouse over an area, a box will appear displaying info about the area. If you place your mouse over that box and move it while it is there, it will detect movement and thus it will try to create again the box. This results in blinking.

**Comment by twolfvb** [comment]
A potential solution is to move the mouse hover tooltip to other particular place, instead of right over the mouse. It could help visibility and get rid of this problem altogether.

**Comment by twolfvb** [comment]
This was fixed on e9c3ddcc5743534c0da005dcb91ba86333fd966e

**Comment by madestro** [comment]
lgtm
